### ISSUE TITLE
Continuum status in tmux status line

### ISSUE THREAD

**Issue by jesusguevarautomotriz** [chilicuil/tundle-plugins#1]
Hi, I'm using tmux 1.8. Can this version of the tmux-continuum plugin show "Continuum status in tmux status line" as in its original version? https://github.com/tmux-plugins/tmux-continuum/blob/master/docs/continuum_status.md Thanks, Regards.

Hola, estoy usando tmux 1.8. Puede esta version del plugin tmux-continuum mostrar "Continuum status in tmux status line" como en su version original? https://github.com/tmux-plugins/tmux-continuum/blob/master/docs/continuum_status.md Gracias, Saludos.

**Comment by javier-lopez** [comment]
Hello,

Commit https://github.com/javier-lopez/tundle-plugins/commit/fcb640bf710da6582e17a425e6c2f458cadc532d adds experimental support for `#{continuum_status}`, please let me know if it works for your case.

Regards

**Comment by jesusguevarautomotriz** [comment]
Hi, 

After some tests, tmux shows tmux-continuum status (display "Continuum status:  ") in tmux status line but, dont display any value, as it is blank.

In my case, i have at tmux.conf:
setenv -g @continuum-save-interval '10' #in minutes

Lubuntu 14.04, bash 4.3.11, Tmux 1.8
